CREATE DATABASE COLLEGE;
CREATE DATABASE XYZ_COMPANY;

DROP DATABASE XYZ_COMPANY;

USE COLLEGE;

CREATE TABLE STUDENT (
ROLL_NO int, 
NAME varchar(30),
AGE INT
);

INSERT INTO STUDENT
VALUES
(101, "ADAM", 12),
(102, "BOB", 14);

SELECT * FROM STUDENT;

CREATE DATABASE IF NOT EXISTS INSTAGRAM;

SHOW DATABASES;

USE INSTAGRAM;

CREATE TABLE USER (
ID int,
AGE INT,
NAME VARCHAR(30) NOT NULL,
EMAIL VARCHAR(50) UNIQUE,
FOLLOWERS int DEFAULT 0,
FOLLOWING int,
CONSTRAINT CHECK(AGE>=13),
PRIMARY KEY (ID)
);

INSERT INTO USER VALUES
(1, 14, "ADAM", "adam@yahoo.com", 123, 145),
(2, 15, "BOB", "bob2121@gmail.com", 221, 200),
(3, 18, "CASEY", "casey77@gmail.com", 355, 206),
(4, 16, "DONALD", "donaldduck@gmail.com", 269, 301);


SELECT ID, NAME, AGE FROM USER;

SELECT * FROM USER;

SELECT DISTINCT AGE FROM USER;

SELECT * FROM USER WHERE FOLLOWERS >=200;

SELECT NAME, FOLLOWERS FROM USER WHERE FOLLOWERS >=200;

SELECT NAME, AGE
FROM USER
WHERE AGE>15;

SELECT NAME, AGE, FOLLOWERS
FROM USER WHERE
AGE>15 AND FOLLOWERS>200;

SELECT NAME, AGE, FOLLOWERS
FROM USER WHERE
AGE>15 OR FOLLOWERS>200;

SELECT NAME, AGE, FOLLOWERS
FROM USER WHERE
AGE BETWEEN 15 AND 17;

INSERT INTO USER
(ID, AGE, NAME, EMAIL, FOLLOWERS, FOLLOWING)VALUES
(5, 14, "EVE", "eve49@yahoo.com", 288, 377),
(6, 19, "FARAH", "farah@gmail.com", 167,246);

INSERT INTO USER 
(ID, NAME, EMAIL, FOLLOWING)
VALUES
(7, "JATIN", "bhaujatin@gmail.com",246);


SELECT NAME, FOLLOWERS, EMAIL, AGE
FROM USER
WHERE AGE IN (14,16);

SELECT NAME, FOLLOWERS, EMAIL, AGE
FROM USERS
WHERE AGE NOT IN (14,16);

SELECT NAME, AGE, EMAIL
FROM USER WHERE AGE>14
LIMIT 2;

SELECT NAME, AGE, FOLLOWERS
FROM USER
ORDER BY FOLLOWERS ASC;

SELECT NAME, AGE, FOLLOWERS
FROM USER
ORDER BY FOLLOWERS DESC;


SELECT MAX(FOLLOWERS)
FROM USER;

SELECT MAX(AGE)
FROM USER;

SELECT MIN(AGE)
FROM USER;

SELECT AVG(AGE) 
FROM USER;

SELECT COUNT(FOLLOWERS)
FROM USER;

SELECT SUM(FOLLOWERS)
FROM USER
WHERE AGE BETWEEN 14 AND 18;

SELECT COUNT(AGE)
FROM USER
WHERE AGE=14;

SELECT NAME, FOLLOWERS, EMAIL
FROM USER
WHERE EMAIL IN
("donaldduck@gmail.com","bob2121@gmail.com");

SELECT AGE,COUNT(ID)
FROM USER
GROUP BY AGE;

SELECT AGE, MAX(FOLLOWERS)
FROM USER GROUP BY AGE;

SELECT AGE, MAX(FOLLOWERS)
FROM USER GROUP BY AGE
HAVING MAX(FOLLOWERS)>250;

SELECT AGE, MAX(FOLLOWERS)
FROM USER
GROUP BY AGE
HAVING MAX(FOLLOWERS)>250
ORDER BY AGE DESC;

UPDATE USER
SET FOLLOWERS=600
WHERE AGE=16;

SET SQL_SAFE_UPDATES=0;

SELECT * FROM USER;

DELETE FROM USER
WHERE AGE=14;

ALTER TABLE USER
ADD COLUMN CITY VARCHAR(25)
DEFAULT "MUMBAI";

ALTER TABLE USER
DROP COLUMN AGE;

ALTER TABLE USER
RENAME TO INSTAUSER;

ALTER TABLE INSTAUSER
RENAME TO USER;

SELECT * FROM INSTAUSER;


ALTER TABLE USER
CHANGE COLUMN FOLLOWERS SUBS INT DEFAULT(0);

ALTER TABLE USER
MODIFY SUBS INT DEFAULT 5;

TRUNCATE TABLE USER;


DROP TABLE POSTS;






CREATE TABLE POSTS (
ID INT PRIMARY KEY,
CONTENT VARCHAR(100),
USER_ID INT,
FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);













